=== fusion-rx/fusion-rx/cli/src/fusion/workspace/schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$id": "SchematicsFusionProjectConfig",
    "title": "Fusion Project Config Schema",
    "type": "object",
    "description": "Defines a fsnconfig.json file.",
    "additionalProperties": false,
    "required": ["name", "version"],
    "properties": {
        "$schema": {
            "type": "string"
        },
        "name": {
            "description": "The name of the Fusion workspace.",
            "type": "string"
        },
        "version": {
            "description": "The version of this workspace",
            "type": "string"
        },
        "newProjectsRoot": {
            "description": "The directory in which new Fusion projects will be generated relative to this file.",
            "type": "string"
        },
        "projects": {
            "description": "Defines projects managed in this workspace by Fusion.",
            "type": "object",
            "patternProperties": {
                "^(?:@[a-zA-Z0-9._-]+/)?[a-zA-Z0-9._-]+$": {
                    "$ref": "#/definitions/project"
                }
            }
        },
        "workspaces": {
            "description": "Defines workspaces that will be managed by Fusion.",
            "type": "object",
            "patternProperties": {
                "^(?:@[a-zA-Z0-9._-]+/)?[a-zA-Z0-9._-]+$": {
                    "$ref": "#/definitions/workspace"
                }
            }
        }
    },
    "definitions": {
        "workspace": {
            "description": "Defines a workspace",
            "type": "object",
            "additionalProperties": false,
            "required": ["projects"],
            "properties": {
                "root": {
                    "description": "Root of the project files.",
                    "type": "string"
                },
                "sourceRoot": {
                    "description": "The root of the source files and assets.",
                    "type": "string"
                },
                "outDir": {
                    "description": "The output directory of the project builds relative to `root`. If undefined, will not create the output directory prior to building.",
                    "type": "string"
                },
                "projects": {
                    "description": "Defines workspaces that will be managed by Fusion.",
                    "type": "object",
                    "patternProperties": {
                        "^(?:@[a-zA-Z0-9._-]+/)?[a-zA-Z0-9._-]+$": {
                            "$ref": "#/definitions/project"
                        }
                    }
                }
            }
        },
        "project": {
            "description": "Defines properties for a project in this workspace",
            "type": "object",
            "additionalProperties": false,
            "required": ["projectType", "root"],
            "properties": {
                "projectType": {
                    "description": "Specify if the project is an application or library",
                    "type": "string",
                    "enum": ["application", "library"]
                },
                "root": {
                    "description": "The source of the project relative to this configuration file.",
                    "type": "string"
                },
                "sourceRoot": {
                    "description": "The root of the source files and assets relative to this configuration file.",
                    "type": "string"
                },
                "architect": {
                    "type": "object",
                    "additionalProperties": false,
                    "properties": {
                        "build": {
                            "$ref": "#/definitions/build"
                        },
                        "serve": {
                            "$ref": "#/definitions/serve"
                        },
                        "test": {
                            "$ref": "#/definitions/test"
                        }
                    }
                }
            }
        },
        "build": {
            "description": "Options that control the build.",
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "builder": {
                    "description": "The builder used to compile the project's source code.",
                    "type": "string",
                    "enum": ["parcel", "tsc"]
                },
                "options": {
                    "type": "object",
                    "additionalProperties": false,
                    "properties": {
                        "outputPath": {
                            "description": "The output path of the project, relative to this configuration file.",
                            "type": "string"
                        },
                        "main": {
                            "description": "The entrypoint of the application, such as main.ts or index.ts, relative to root.",
                            "type": "string"
                        },
                        "tsConfig": {
                            "description": "The name of the tsconfig file used to build the application.",
                            "type": "string"
                        },
                        "assets": {
                            "description": "Assets to include in the build",
                            "type": "array"
                        },
                        "targets": {
                            "type": "object",
                            "patternProperties": {
                                "^(?:@[a-zA-Z0-9._-]+/)?[a-zA-Z0-9._-]+$": {
                                    "$ref": "#/definitions/target"
                                }
                            }
                        }
                    }
                }
            }
        },
        "serve": {
            "type": "object",
            "additionalProperties": false
        },
        "test": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "builder": {
                    "description": "A unit test library.",
                    "type": "string",
                    "enum": ["jest"]
                },
                "options": {
                    "type": "object",
                    "additionalProperties": false,
                    "properties": {
                        "main": {
                            "description": "The entry test file relative to root.",
                            "type": "string"
                        },
                        "tsConfig": {
                            "description": "The name of the tsconfig file used to build the application.",
                            "type": "string"
                        },
                        "jestConfig": {
                            "description": "The name of the jest configuration file.",
                            "type": "string"
                        },
                        "assets": {
                            "description": "Assets to include in the build",
                            "type": "array"
                        }
                    }
                }
            }
        },
        "target": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "context": {
                    "type": "string",
                    "enum": [
                        "browser",
                        "web-worker",
                        "service-worker",
                        "worklet",
                        "node",
                        "electron-main",
                        "electron-renderer"
                    ]
                },
                "outputFormat": {
                    "type": "string",
                    "enum": ["esmodule", "commonjs", "global"]
                }
            }
        }
    }
}

=== fusion-rx/fusion-rx/fusion.json
{
    "$schema": "./cli/src/fusion/workspace/schema.json",
    "name": "Fusion-rx",
    "version": "0.1.0",
    "newProjectsRoot": "packages",
    "projects": {
        "example": {
            "projectType": "application",
            "root": "packages/example",
            "sourceRoot": "packages/example/app",
            "architect": {
                "build": {
                    "builder": "tsc",
                    "options": {
                        "outputPath": "dist",
                        "main": "main.ts",
                        "tsConfig": "tsconfig.app.json"
                    }
                },
                "test": {
                    "builder": "jest",
                    "options": {
                        "main": "src/test.ts",
                        "tsConfig": "tsconfig.spec.ts",
                        "jestConfig": "jest.conf.js"
                    }
                }
            }
        },
        "shared": {
            "projectType": "library",
            "root": "packages/shared",
            "sourceRoot": "packages/shared/src",
            "architect": {
                "build": {
                    "builder": "tsc",
                    "options": {
                        "outputPath": "dist",
                        "main": "public-api.ts",
                        "tsConfig": "tsconfig.build.json"
                    }
                },
                "test": {
                    "builder": "jest",
                    "options": {
                        "main": "test.ts",
                        "tsConfig": "tsconfig.spec.ts",
                        "jestConfig": "jest.conf.js"
                    }
                }
            }
        },
        "core": {
            "projectType": "library",
            "root": "packages/core",
            "sourceRoot": "packages/core/src",
            "architect": {
                "build": {
                    "builder": "tsc",
                    "options": {
                        "outputPath": "dist",
                        "main": "public-api.ts",
                        "tsConfig": "tsconfig.build.json",
                        "targets": {
                            "main": {
                                "context": "node",
                                "outputFormat": "commonjs"
                            },
                            "module": {
                                "context": "browser",
                                "outputFormat": "esmodule"
                            }
                        }
                    }
                },
                "test": {
                    "builder": "jest",
                    "options": {
                        "main": "test.ts",
                        "tsConfig": "tsconfig.spec.ts",
                        "jestConfig": "jest.conf.js"
                    }
                }
            }
        },
        "common": {
            "projectType": "library",
            "root": "packages/common",
            "sourceRoot": "packages/common/src",
            "architect": {
                "build": {
                    "builder": "tsc",
                    "options": {
                        "outputPath": "dist",
                        "main": "public-api.ts",
                        "tsConfig": "tsconfig.build.json"
                    }
                },
                "test": {
                    "builder": "jest",
                    "options": {
                        "main": "test.ts",
                        "tsConfig": "tsconfig.spec.ts",
                        "jestConfig": "jest.conf.js"
                    }
                }
            }
        },
        "test": {
            "projectType": "library",
            "root": "packages/test",
            "sourceRoot": "packages/test/src",
            "architect": {
                "build": {
                    "builder": "tsc",
                    "options": {
                        "outputPath": "dist",
                        "main": "public-api.ts",
                        "tsConfig": "tsconfig.build.json"
                    }
                },
                "test": {
                    "builder": "jest",
                    "options": {
                        "main": "test.ts",
                        "tsConfig": "tsconfig.spec.ts",
                        "jestConfig": "jest.conf.js"
                    }
                }
            }
        }
    }
}
